server:
  port: 8080

spring:
  application:
    name: gym
  datasource:
    url: jdbc:mysql://localhost:3306/gym?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    favicon:
      enabled: false
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  profiles:
    active: "@spring.profiles.active@"
    include: log

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: site.layne666.gym.pojo
